### START SERVER json-server --watch db.json


### GET
http://localhost:8000/usuarios

### POST
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "userName": "rfrancacosta22",
    "password": "123456"
}

### PUT
PUT http://localhost:3000/users/8 HTTP/1.1
content-type: application/json

{
    "userName": "rfrancacosta23",
    "password": "123456"
}

### DELETE
DELETE http://localhost:3000/users/8 HTTP/1.1

### GET/ID
http://localhost:3000/users/1